### ISSUE TITLE
Create Custom Board

### ISSUE THREAD

**Issue by bobbydilley** [bobbydilley/OpenJVS#20]
Create the custom OpenJVS Board

**Comment by dogtopus** [comment]
I recently dug out my (non-working) JVS shield project and am attempting to fix it. The process went smoothly so far. I may release the schematic and board layout after I finished fixing it. It was for Arduino but could be easily adopted as RPi HAT.

Some feature highlights:

- Dual voltage support (3.3v and 5v)
- Dual role (host (node 0) and device)
  - Supports daisy-chain setup
- On-demand termination enable/disable
- Proper SENSE line input and output
  - SENSE detection is comparator-based and works without ADC (one of the reason why it is easy to port to RPi)
  - Fool-proof SENSE line driving (in case somebody decided to plug it into USB port)

**Comment by bobbydilley** [comment]
Your board sounds really good, very cool that you support the proper daisy chaining setup!

I'd love to work together if you would be interested in making a board to use with OpenJVS! I could send you the details for which Pi pins are needed etc?
