### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by bobbydilley** [bobbydilley/OpenJVS#25]
The sensitivity of some of the games it probably wrong, because I suspect we send the analogue high byte first, so every time you move, its moving loads.

Make sure to send the bytes in the correct order, and shift down

**Comment by bobbydilley** [comment]
In retrospect maybe the endianess is correct

**Comment by JayFoxRox** [comment]
Why were all these issues and PRs closed? I can't seem to find any reason.
It caused considerable notification spam for me.

**Comment by bobbydilley** [comment]
Appologies, the repostitory is going to be archived. Please unfollow this one, and follow the main repository at https://github.com/openjvs/openjvs if you are still interested.
