### ISSUE TITLE
Add Netboot Capabilities

### ISSUE THREAD

**Issue by bobbydilley** [bobbydilley/OpenJVS#9]
There is already some C code online for netbooting, so shouldn't be hard.

Wanting to try and make it locate the Naomi using a `nmap -sn 10.0.0.*` sort of command, although the IP could just be put in the config.

Add to global config:

```
NETBOOT_IP 10.0.0.25
NETBOOT_ROMS_FOLDER ~/.openjvs/roms/
```

Add to each game config:

```
NETBOOT_GAME crazy_taxi.bin
```

**Comment by bobbydilley** [comment]
Have done this - currently IP is in the configuration file, and there is no NETBOOT_GAME setting only chooses the rom with the same name.

- Need to do the nmap thing
- Need to add the setting in for NETBOOT_GAME

**Comment by itslemcy** [comment]
would be cool to support an i2c touchscreen such as https://www.adafruit.com/product/1983

**Comment by bobbydilley** [comment]
I am thinking of creating a custom board with a small OLED screen on it, however if the i2c touch screen isn't too expensive, and I can fit it onto a board that is compatible with the pins required to run OpenJVS I'd be more than happy to add this!

**Comment by itslemcy** [comment]
Count me in if you need help!

**Comment by bobbydilley** [comment]
> Count me in if you need help!

Thank you very much for the offer. Feel free to find my email at https://dilley.io/contact and email me, and we can see about adding you onto the project!
